### ISSUE TITLE
Improve parsing speed

### ISSUE THREAD

**Issue by Mintonne** [Pustur/whatsapp-chat-parser#12]
Hey,

Is there a way to improve the parsing times?

#### Firefox 67.0 (64-bit)

```
Parsed 8129 messages in 721 ms
Parsed 20251 messages in 4720 ms
Parsed 40645 messages in 20498 ms
```

#### Edge Chromium Version 76.0.167.1 (Official build)

```
Parsed 8129 messages in 569 ms
Parsed 20251 messages in 2705 ms
Parsed 40645 messages in 12423 ms
```

The duration is almost 2x/3x on low to mid-end smartphones.

**Comment by Pustur** [comment]
Thanks for the report. I have never concerned myself with speed while developing this package (I just wanted to get this working properly first) and I know that parsing long chats takes a long time.

I'll see what I can do about it.

**Comment by Mintonne** [comment]
`makeArrayOfMessages` function seems to be the bottleneck.

```
Splitting file: 11.099ms
makeArrayOfMessages: 8018.587ms
parseMessages: 162.110ms
Parsed 40645 messages successfully
```

**Comment by Pustur** [comment]
Hey, found the issue.

I was using `concat` in a loop and apparently it was very expensive. Switching to a `push` approach helped a ton!

40000 messages used to take ~8.5s, now just ~17ms

I pushed the changes to [feature/perf-improvements](https://github.com/Pustur/whatsapp-chat-parser/tree/feature/perf-improvements) if you want to check them out.

Would you mind testing the performance with the new build and report back? For now I tested only with node `v11.14.0`

Here's the dist files so you don't have to compile them yourself: [dist.zip](https://github.com/Pustur/whatsapp-chat-parser/files/3239117/dist.zip)

**Comment by Mintonne** [comment]
That is a huge performance improvement.

I will try it out on a browser then let you know.

**Comment by Pustur** [comment]
Great to hear that it's fixed! Thank you so much for bringing this to my attention 😄  
`v2.0.1` is now available
