### ISSUE TITLE
Different languages format support

### ISSUE THREAD

**Issue by JGStyle** [Pustur/whatsapp-chat-parser#225]
I like your library! Unfortunately different languages generate the file differently. For example a chat history file generated on a German phone looks like this "[19.04.17, 20:43:09] John Doe: ‎message 123". Is there any way this could be supported?

**Comment by Pustur** [comment]
Hello, seems to me like it works with the format that you provided. Could you share more details?

Link of working code: https://runkit.com/pustur/60b27afbfba8c4001a0d86bb

**Comment by JGStyle** [comment]
Turns out there was a mistake in my file. Sorry to bother you!

**Comment by Pustur** [comment]
Ok no problem, glad you found my library useful :)
