### ISSUE TITLE
parseAttachments stopped working with the new whatsapp exports.

### ISSUE THREAD

**Issue by gmm8ljs** [Pustur/whatsapp-chat-parser#231]
Tried to parse chats from my WhatsApp group and parseAttachments was not working, I think whatsapp had changed the format for including media

Even after using parseAttachments, I am getting this as output:
{
      "date": "2021-04-28T02:00:00.000Z",
      "author": "+91 77606 66008",
      "message": "IMG-20210428-WA0001.jpg (file attached)"
}
<img width="484" alt="Screenshot 2021-06-01 at 11 55 36 AM" src="https://user-images.githubusercontent.com/50130065/120276685-a4467880-c2d0-11eb-9e42-6aa9713bc721.png">

**Comment by Pustur** [comment]
Hello and thanks for reporting the issue.

I changed the regex for the attachment parser to include this new format.

Should work with the new version `3.1.3`, feel free to reopen the issue if you still have problems 👍

**Comment by gmm8ljs** [comment]
Thank you, Great work.
