### ISSUE TITLE
Sync parseString

### ISSUE THREAD

**Issue by mlomb** [Pustur/whatsapp-chat-parser#236]
Is it possible to have a non Promise version of `parseString`? Maybe `parseStringSync`?
Reading `index.ts` seems like the input string is being passed to `makeArrayOfMessages` then the result to `parseMessages`, but neither of them returns a promise. So, is there a reason why the function should return a Promise?
I'm using the library in a context where I don't want async. Making it async forces me to use async everywhere.

**Comment by Pustur** [comment]
Hello,

Yes looking back at the code the use of promises here is not really necessary. I followed your suggestion and added `parseStringSync` method in `3.2.0`. 

I hope this fixes your problem, feel free to reopen the issue if needed.
