### ISSUE TITLE
Attachment doesn't display

### ISSUE THREAD

**Issue by Drjacky** [Pustur/whatsapp-chat-parser#244]
The value is `<attached: 00000040-PHOTO-2021-08-30-22-21-40.jpg>` for example. But it still displays it as plain text.
My implementation:  
<img width="262" alt="Screen Shot 2022-10-23 at 11 49 19" src="https://user-images.githubusercontent.com/2296754/197387939-f4800e36-f0e7-4564-b421-35e29daabe6a.png">

________
Another question, does your app on netlify(https://whatsapp-chat-parser.netlify.app/) suppose to support attachments or not?
Your app:  
<img width="261" alt="Screen Shot 2022-10-23 at 11 48 45" src="https://user-images.githubusercontent.com/2296754/197387901-56d7d394-a752-4351-85ae-b1f6e573e83b.png">

**Comment by Pustur** [comment]
Hi @Drjacky 

Did you upload a zip file or a txt file? Using a txt file will not show the attachments

**Comment by Drjacky** [comment]
My bad. I uploaded `.txt`. and not the `.zip`.

I've created another issue on the website repo: https://github.com/Pustur/whatsapp-chat-parser-website/issues/20
Would be appreciated if you could take a look into that one too. 🙏🏻
