### ISSUE TITLE
Extraction of file names  (attachments) failed sometimes

### ISSUE THREAD

**Issue by detlefm** [Pustur/whatsapp-chat-parser#260]
There is a problem with the recognition of file names of attachments (German export of WhatsApp chats). In my short test, the file names that have non-numeric characters before the dot in the file name are not recognized or only partially recognized and then of course not found in the zip file.

From the sample data:
  {
    date: 2019-06-20T14:03:55.000Z,
    author: 'Loris',
    message: '<attached: 00000003-AUDIO-2019-06-20-16-03-55.mp3>',
    attachment: { fileName: '00000003-AUDIO-2019-06-20-16-03-55.mp3' }
  }
-- > correct found, even with non-numeric chars

From my export:
 {
    date: 2021-04-04T07:40:00.000Z,
    author: 'Detlef',
    message: '‎4f2680f1db95a8454775cc2eefc95bfc.jpg (Datei angehängt)\n' +
      'Dir auch frohe Ostern.'
  },  ->> not recognized
 {
    date: 2021-12-26T09:21:00.000Z,
    author: 'Detlef',
    message: '‎43e5d8acf55f3cdfd7176398c1f72300.jpg (Datei angehängt)\n' +
      'Weihnachtsgrüße.\n',
    attachment: { fileName: '72300.jpg' }
  },  --> partially
{
    date: 2020-10-24T07:58:00.000Z,
    author: 'Detlef',
    message: '‎a8ffb9388ac7c918f674976d03b500dc.jpg (Datei angehängt)\n' +
      'Herbst.'
  }, ->> not recognized
  {
    date: 2020-10-25T09:08:00.000Z,
    author: 'Günter',
    message: '‎9591ded494954f284331518780909901.jpg (Datei angehängt)\n' +
      'alles O.K.bei mir',
    attachment: { fileName: '284331518780909901.jpg' }
  },  --> partially

**Comment by detlefm** [comment]
I've built up some JavaScript and Typescript know-how (with the help of DeepSeek) to see how attachments are actually detected. Our solution is this:
``` javascript
const regexAttachment = /(?:^|\s|[<>:"/\\|?*])([\w-]+\.\w+)(?=$|\s|[<>:"/\\|?*])/;

function parseMessageAttachment(message) {
  // Entferne das unsichtbare Zeichen [U+200E]
  const cleanedMessage = message.replace(/\u200E/g, ' ');

  const attachmentMatch = cleanedMessage.match(regexAttachment);

  if (!attachmentMatch) return null;
  return {
    fileName: attachmentMatch[1].trim(),
  };
}

// Beispielaufruf
const inputString1 = '‎b200c462d3079f50d8b374728a3405a3.jpg (Datei angehängt)\n';
const inputString2 = '<attached: 00000001-PHOTO-2019-06-20-16-00-15.jpg>';

const attachment1 = parseMessageAttachment(inputString1);
const attachment2 = parseMessageAttachment(inputString2);

console.log(attachment1);  // Ausgabe: { fileName: 'b200c462d3079f50d8b374728a3405a3.jpg' }
console.log(attachment2);  // Ausgabe: { fileName: '00000001-PHOTO-2019-06-20-16-00-15.jpg' }
```

We assume that the file name cannot be a path, since all attachments are in the root of the ZIP file. The file name always has a suffix. And the peculiarities and limitations of the Windows file system come into play (special characters, etc.). We also assume that the file name does not contain spaces, since it is generated by WhatsApp and not by the user. Of course, there is no security when parsing. The user could write a valid file name and some text before or after it. And by chance, this exactly matches the output of WhatsApp in any language. Actually, you should then compare the names of the attachments found with the existing files and, if they are not there, interpret them as user text. Or give the parser routine the file names straight away and it can check whether the result is valid.

**Comment by detlefm** [comment]
If you only want to analyze the text file, one way to avoid misinterpretation (attachment or not) would be to analyze all lines recognized as attachments. In addition to the actual file name, they would have to have the same pattern. So the prefix and suffix (if there is one) would be identical. This is possible when entering a file name manually, but not likely. And if you have the option of saving this pattern for the user, you would have a kind of self-learning recognition.

**Comment by Pustur** [comment]
Hi @detlefm 
I found that the main problem was that I assumed the filenames were always uppercase, which is not the case. I changed the regex to be more loose, and that should be enough to parse your attachments.

Would you be able to confirm by testing yor chats with this?
[whatsapp-chat-parser-4.0.2-beta.tgz](https://github.com/user-attachments/files/17077228/whatsapp-chat-parser-4.0.2-beta.tgz)

You can install with `npm install path/to/whatsapp-chat-parser-4.0.2-beta.tgz`

**Comment by Pustur** [comment]
> The captions are saved as a second line. But if the web interface corrects this

That's a separate issue (#261) that I'll look into another time.

> The times are shifted during conversion

What you are seeing in the parsed object is a date representation without timezone information.
As long as the application that is used to parse the chat log has the same timezone offset as the whatsapp device that generated the chat, you should not see any shifts.

This is me showing (in the browser console) how I get back the correct date from the first example you provided:
![image](https://github.com/user-attachments/assets/b5bc35e3-369f-47f3-9011-858e563064a5)

**Comment by detlefm** [comment]
The thing about the normalization of time is clear. But why there are differences in the two chats (neither of which have stored time zone information) is not so clear to me - but I'm not familiar with the topic and it has nothing to do with the reported bug. In any case, this bug has been resolved for now.

**Comment by Pustur** [comment]
> But why there are differences in the two chats (neither of which have stored time zone information)

That's a wrong assumption, the exported chat log has the dates shifted by the timezone of the device that generated them.

It makes sense in a way. If i text my friend at 18:00 (CEST timezone) and then export the chat, it would be a bit strange to see the date changed to 16:00 (No timezone), so they keep it at 18:00.

This is problematic when the computer that parses that chat is set to a different timezone, because then they won't match anymore and you'll have a consistent shift on all the dates.

If you're confused about why we are in the same timezone but your example the date is shifted 1h and in mine it's 2h, that's because of daylight savings. CEST is either +1h or +2h depending on that.

I hope it's clearer now, dates and timezones are notoriously confusing / complex.

PS: I'll reopen the issue since technically it's still not fixed (i have not published the fixed version yet). It will close automatically when i merge develop branch into master.

**Comment by detlefm** [comment]
Now I'm completely confused. I'm attaching three files:
Loris.txt (a line from your sample chat), Detlef.txt (a line from my chat). No information about where, how, when, who chatted or exported. And an xstart.js (renamed to xstart.txt because of github) that executes a parseString for both files. Here is the plain text:
Loris:    
```
[20.06.19, 16:03:38] Loris: Ok, let me share an audio file
```
Detlef:
```
26.12.21, 10:21 - Detlef : Weihnachtsgrüße.
```
Output
```
[
  {
    date: 2021-12-26T09:21:00.000Z,
    author: 'Detlef ',
    message: 'Weihnachtsgrüße.'
  }
// Converted to UTC 1 hour diff
]
[
  {
    date: 2019-06-20T14:03:38.000Z,
    author: 'Loris',
    message: 'Ok, let me share an audio file'
  }
// Converted to UTC 2 hours diff
]
```
[loris.txt](https://github.com/user-attachments/files/17080002/loris.txt)
[detlef.txt](https://github.com/user-attachments/files/17080006/detlef.txt)
[xstart.txt](https://github.com/user-attachments/files/17080016/xstart.txt)

**Comment by Pustur** [comment]
That difference as I said previously is due to daylight savings.

my date is in june `20.06.19, 16:03:38` so the offset is +2h

your date is in december `26.12.21, 10:21` so the offset is +1h

For this year for example, the daylight savings period where the time is +2h is the following:
Sun, Mar 31, 2024 – Sun, Oct 27, 2024

I can confirm this in the browser console, you see the first date has +2 offset, while the second has +1 offset:
![Screenshot 2024-09-20 213104](https://github.com/user-attachments/assets/c0155996-f6db-42b7-a840-c0df87d91cea)

Is that clearer now?

**Comment by detlefm** [comment]
Thanks for your patience - sometimes it takes me longer.
