### ISSUE TITLE
Build script: "rm -rf" not available in windows

### ISSUE THREAD

**Issue by Pustur** [Pustur/whatsapp-chat-parser#29]
https://github.com/Pustur/whatsapp-chat-parser/blob/a373ff1c90f7bfe48260c430e956d973bebd34c5/package.json#L10

`rm -rf` used to remove the `dist/` folder before rebuilding the files is not available in windows.

Consider a cross-platform solution (`rimraf`?).

**Comment by Mintonne** [comment]
rimraf should do. I also did not test it on CMD.

**Comment by Pustur** [comment]
`rimraf` works well on my mac and pc. Closing this.
