### ISSUE TITLE
Add type definitions for Typescript

### ISSUE THREAD

**Issue by Pustur** [Pustur/whatsapp-chat-parser#60]
I'd like to add type definitions but I don't have any experience with Typescript yet.  
The definition would be for the public API, so just this function:

https://github.com/Pustur/whatsapp-chat-parser/blob/9d78a686ea2604475779866019d5eec098c2dce9/src/index.js#L7

The API is pretty well documented in the readme.

I'd like to have a `types` folder in the root of the project, with a `index.d.ts` file inside.  
When done, a PR can be opened against the `develop` branch.

Anyone interested in taking this? Would be very appreciated.

**Comment by Cretezy** [comment]
```typescript

interface ParseStringOptions {
  daysFirst?: boolean;
}

export function parseString(string: string, options: ParseStringOptions);
```

Place in root as `whatsapp-chat-parser.d.ts`.

In `package.json`:
- If `files` is set, add there
- Add `"types": "whatsapp-chat-parser.d.ts"` on root

**Comment by Pustur** [comment]
@Cretezy Thank you very much! I made some small adjustments but otherwise your code works very well!
