### ISSUE TITLE
How do I run this on my computer?

### ISSUE THREAD

**Issue by timeakesmarky** [Pustur/whatsapp-chat-parser#74]
I installed npm install whatsapp-chat-parser

What next? I don't know how to open it.

**Comment by Pustur** [comment]
Hi @timeakesmarky 

You can follow the documentation for [Node.js](https://github.com/Pustur/whatsapp-chat-parser#node) or the [Browser](https://github.com/Pustur/whatsapp-chat-parser#browser) depending on which one better suits your needs.

Just to be clear, this package is just a helper function that converts a whatsapp chat from text format to an array of structured messages. It's meant to be used as part of a program, it's not something you can "open" by itself.

If you just want to see an exported whatsapp chat in a readable format, you may find my other project [whatsapp-chat-parser-website](https://github.com/Pustur/whatsapp-chat-parser-website) helpful.

If you tell me what you're trying to do, I may be able to help you further.

**Comment by timeakesmarky** [comment]
I want to use this locally without internet so that I can read lots of my messages.
Also, how to export all the chats as txt on whatsapp? It seems to have a limit of around 40000 messages.

**Comment by Pustur** [comment]
I prepared a build of the static website so you can use it offline. You'll need to use a local server to serve it but it's pretty easy.

1. Download the files for the website 👉 [build.zip](https://github.com/Pustur/whatsapp-chat-parser/files/3602424/build.zip)
2. Extract the `zip` file wherever you want
3. Open a terminal window and navigate to the extracted folder
4. Serve the files using a package like [http-server](https://www.npmjs.com/package/http-server)
5. Be warned that if you're trying to view 40000 messages you'll have to change the setting in the sidebar (by default it limits the messages to the first 100) but if you set it to a very high number it will take a lot of time to render all the messages. I tried it on my pc and it took about 30 seconds to render 40000 messages, so just give it a bit of time and it'll work

> Also, how to export all the chats as txt on whatsapp? It seems to have a limit of around 40000 messages.

Unfortunately this seems to be a WhatsApp limitation and I don't know if you can circumvent it, sorry

**Comment by timeakesmarky** [comment]
Thank you! It works. Is there a method to build myself in case there are new versions?

**Comment by Pustur** [comment]
I just added the built files for each version in the releases section of the repo:
[whatsapp-chat-parser-website/releases](https://github.com/Pustur/whatsapp-chat-parser-website/releases)  
(It's the one called `whatsapp-chat-parser-website-<version>.tgz`)
I'll add the release notes as well when I have more time.

If you want to be notified when I release a new version just click the watch button and select "Releases only"
<img width="307" alt="Screenshot 2019-09-11 at 22 36 55" src="https://user-images.githubusercontent.com/13663338/64733289-bffa6180-d4e4-11e9-8174-a8eb8df8d861.png">

Just be sure to do it in the `whatsapp-chat-parser-website` repo and not this one 😄

**Comment by timeakesmarky** [comment]
Wow, thank you so much!

**Comment by Pustur** [comment]
No problem, I'll close this for now.  
If you face any problems with the site feel free to open an issue there.
